name: Create Version PR

on:
  push:
    branches:
      - releases
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  version:
    if: |
      github.event_name != 'push' ||
      (!contains(github.event.head_commit.message, 'chore: release version') &&
       !startsWith(github.event.head_commit.message, 'Prepare Release'))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Set up Git identity
        run: |
          git config user.name "Govind Kumar"
          git config user.email "govind.kumar@incsub.com"

      - name: Run Changesets to create version PR
        uses: changesets/action@v1
        with:
          title: 'Prepare Release'
          commit: 'chore: release version'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
