name: Deploy & Release

on:
  pull_request:
    types: [closed]
    branches:
      - releases

jobs:
  release:
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.title, 'Prepare Release')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

#      - name: Run Changeset Release
#        run: npm run release

      - name: Get version from package.json
        id: version
        run: echo "VERSION=v$(node -p \"require('./package.json').version\")" >> $GITHUB_OUTPUT

      - name: Extract latest changelog entry
        id: changelog
        run: |
          VERSION=${{ steps.version.outputs.VERSION }}
          awk -v version="## $VERSION" '
            BEGIN {print_flag=0}
            $0 ~ version {print_flag=1; next}
            /^## / && print_flag {exit}
            print_flag {print}
          ' CHANGELOG.md > RELEASE_BODY.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          name: Release ${{ steps.version.outputs.VERSION }}
          body_path: RELEASE_BODY.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}